services:
  - type: web
    name: agendavirtualeiwa
    runtime: python
    buildCommand: "pip install -r AgendaVirtualEiwa/requirements.txt && cd AgendaVirtualEiwa && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "cd AgendaVirtualEiwa && gunicorn AgendaVirtualEiwa.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agendavirtualeiwa-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: agendavirtualeiwa-db
    databaseName: agendavirtualeiwa
    user: agendavirtualeiwa
